# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://server.natappfree.cc:44988/blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456789
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml